config/routes.rb
Rails.application.routes.draw do
  root 'vacancies#index'

  resources :skills, only: [:index, :create, :destroy]

  resources :vacancies do
    resources :skills, only: [:create, :destroy]
  end

  resources :employees do
    resources :skills, only: [:create, :destroy]
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_and_belongs_to_many :skills

  validates :name, :contacts, :salary, :status, presence: true
  validates :name, format: {
      with: /\A[А-Яа-я]+ [А-Яа-я]+ [А-Яа-я]+\z/,
      message: 'ФИО должно быть на кириллице и содержать 3 слова'}
  validates :contacts, format: {
      with: /(\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z|^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$)/,
      message: 'Допускаются только email или телефонный номер' }
  validates :salary, numericality: true

  def skills_data=(value)
    skills.clear

    return if value.nil?

    value.uniq.each do |s|
      skill = Skill.find_or_create_by name: s
      skills << skill
    end
  end

  def skills_data
    skills.map { |s| s.name }.to_json
  end

  def suitable

    wholly_suitable_vacancies = []
    partially_suitable_vacancies = []

    vacancies = Vacancy.where(%("vacancies"."expiration_date" > ?), Time.current).order(salary: :desc)
    vacancies.each do |vacancy|
      if vacancy.skills.ids.all? { |e| skills.ids.include?(e) }
        wholly_suitable_vacancies << vacancy
      elsif vacancy.skills.ids.collect { |e| skills.ids.include?(e) }
        partially_suitable_vacancies << vacancy
      end
    end

    suitable_vacancies = {wholly: wholly_suitable_vacancies, partially: partially_suitable_vacancies}
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_and_belongs_to_many :vacancies
  has_and_belongs_to_many :employees

  validates :name, presence: true
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  has_and_belongs_to_many :skills

  validates :name, :expiration_date, :salary, :contacts, presence: true
  validates :salary, numericality: true
  validates :contacts, length: {maximum: 255}

  def skills_data=(value)
    skills.clear

    return if value.nil?

    value.uniq.each do |s|
      skill = Skill.find_or_create_by name: s
      skills << skill
    end
  end

  def skills_data
    skills.map { |s| s.name }.to_json
  end

  def suitable

    wholly_suitable_employees = []
    partially_suitable_employees = []

    employees = Employee.where(status: true).order(:salary)
    employees.each do |employee|
      if skills.ids.all? { |e| employee.skills.ids.include?(e) }
        wholly_suitable_employees << employee
      elsif skills.ids.collect { |e| employee.skills.ids.include?(e) }
        partially_suitable_employees << employee
      end
    end

    suitable_employees = {wholly:  wholly_suitable_employees, partially: partially_suitable_employees}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.order(created_at: :desc)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @suitable_vacancies = @employee.suitable
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Новый работник был успешно создан' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Работник был успешно обновлён' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Работник был успешно удалён' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :contacts, :status, :salary, skills_data: [])
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]

  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.all.order(created_at: :desc)
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
    @suitable_employees = @vacancy.suitable
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Новая вакансия была успешно создана.' }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1
  # PATCH/PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: 'Вакансия была успешно обновлена' }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: 'Вакансия была успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit(:name, :expiration_date, :salary, :contacts, skills_data: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>

    <%= render partial: 'partials/form_errors', locals: {model: @employee} %>

    <div class="form-group">
      <%= f.label :status, 'Ищу работу' %>
      <%= f.radio_button :status, true, checked: true %>
      <%= f.label :status, 'Не ищу работу' %>
      <%= f.radio_button :status, false %>
    </div>

    <div class="form-group">
      <%= f.label :name, 'ФИО' %>
      <%= f.text_field :name, placeholder: 'Только кириллица', class: 'form-control'  %>
    </div>

    <div class="form-group">
      <%= f.label :contacts, 'Контактная информация' %>
      <%= f.text_field :contacts, placeholder: 'Email или номер телефона', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :salary, 'Зарплата' %>
      <%= f.text_field :salary, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :skills_data, 'Навыки' %>
      <%= f.text_field :skills_data, id: 'skills_input' %>
    </div>

    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
    </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Редактирование работника</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>

    <br>
    <%= link_to 'Удалить', employee_path, method: :delete,
                data: {confirm: 'Вы уверены, что хотите удалить работника?'}, class: 'btn btn-danger' %>
  </div>
</div>

app/views/employees/index.html.erb
<h1>Список работников</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <div class="row">
    <div class="col-md-12">
      <div class="list-group">
        <% @employees.each do |employee| %>
            <a href="employees/<%= employee.id %>" class="list-group-item row">
              <div class="col-md-6"><%= employee.name %></div>
              <div class="col-md-6 text-right"><%= employee.salary %> руб.</div>
            </a>
        <% end %>
      </div>
    </div>
  </div>
</table>

<br>

<%= link_to 'Новый работник', new_employee_path, class: 'btn btn-primary' %>

app/views/employees/new.html.erb
<h1>Новый работник</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/employees/show.html.erb
<div class="row">

  <div class="col-md-6">
    <div class="employee-description">
      <h1><%= @employee.name %></h1>
      <p><strong>Зарплата:</strong> <%= @employee.salary %></p>
      <p><strong>Навыки:</strong> <%= @employee.skills.map {|s| s.name}.join(', ') %></p>
      <p><strong>Статус:</strong>
        <% if @employee.status %>
          В поиске
        <% else %>
          Отдыхаю
        <% end %>
      </p>
      <p><strong>Контактная информация:</strong> <%= @employee.contacts %></p>
    </div>
    <%= link_to 'Редактировать', edit_employee_path(@employee) %> |
    <%= link_to 'К списку', employees_path %>
  </div>

  <div class="col-md-6">
    <% if @suitable_vacancies[:wholly].present? %>
      <div class="suitable-vacancies">
        <h3>Полностью подходящие вакансии:</h3>
        <div class="list-group">
          <% @suitable_vacancies[:wholly].each do |e| %>
              <a href="<%= vacancy_path(e) %>" class="list-group-item row">
                <div class="col-md-6"><%= e.name %></div>
                <div class="col-md-6 text-right"><%= e.salary %> руб.</div>
              </a>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @suitable_vacancies[:partially].present? %>
      <div class="suitable-vacancies">
        <h3>Частично подходящие вакансии:</h3>
        <div class="list-group">
          <% @suitable_vacancies[:partially].each do |e| %>
              <a href="<%= vacancy_path(e) %>" class="list-group-item row">
                <div class="col-md-6"><%= e.name %></div>
                <div class="col-md-6 text-right"><%= e.salary %> руб.</div>
              </a>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Dogface" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to 'HR-helper', root_path, class: 'navbar-brand' %>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Вакансии", "/vacancies"  %></li>
        <li><%= link_to "Работники", "/employees"  %></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <!-- <p>&copy; Company 2016</p> -->
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/partials/_form_errors.html.erb
<%# Универсальный паршиал отображения ошибок валидации любой модели %>
<% errors = model.errors %>

<% if errors.any? %>
    <div class="alert alert-danger">
      <div class="lead buffer-bottom">
        В вашей форме <%= errors.count %> <%= Russian.p(errors.count, 'ошибка', 'ошибки', 'ошибок') %>
      </div>

      <ul>
        <% errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Skills</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/vacancies/_form.html.erb
<%= form_for(@vacancy) do |f| %>

    <%= render partial: 'partials/form_errors', locals: {model: @vacancy} %>

    <div class="form-group">
      <%= f.label :name, 'Название' %>
      <%= f.text_field :name, placeholder: 'Название вакансии', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :expiration_date, 'Дата окончания' %>
      <%= f.text_field :expiration_date, placeholder: 'дд.мм.гггг', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :salary, 'Зарплата' %>
      <%= f.text_field :salary, placeholder: 'Рублей', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :contacts, 'Контактная информация' %>
      <%= f.text_field :contacts, placeholder: 'Любая контактная информация', class: 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.label :skills_data, 'Навыки' %>
      <%= f.text_field :skills_data, id: 'skills_input' %>
    </div>


    <div class="actions">
      <%= f.submit 'Сохранить', class: 'btn btn-primary' %> или <%= link_to 'вернуться', :back %>
    </div>

<% end %>

app/views/vacancies/edit.html.erb
<h1>Редактирование вакансии</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>

    <br>
    <%= link_to 'Удалить', vacancy_path, method: :delete,
                data: {confirm: 'Вы уверены, что хотите удалить вакансию?'}, class: 'btn btn-danger' %>
  </div>


</div>

app/views/vacancies/index.html.erb
<h1>Список вакансий</h1>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <div class="row">
    <div class="col-md-12">
      <div class="list-group">
        <% @vacancies.each do |vacancy| %>
            <a href="vacancies/<%= vacancy.id %>" class="list-group-item row">
              <div class="col-md-6"><%= vacancy.name %></div>
              <div class="col-md-6 text-right"><%= vacancy.salary %> руб.</div>
            </a>
        <% end %>
      </div>
    </div>
  </div>
</table>

<br>

<%= link_to 'Новая вакансия', new_vacancy_path, class: 'btn btn-primary' %>

app/views/vacancies/new.html.erb
<h1>Новая вакансия</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'form' %>
  </div>
</div>

app/views/vacancies/show.html.erb
<div class="row">

  <div class="col-md-6">
    <div class="vacancy-description">
      <h1><%= @vacancy.name %></h1>
      <p><strong>Зарплата:</strong> <%= @vacancy.salary %></p>
      <p><strong>Действительна до:</strong> <%= @vacancy.expiration_date %></p>
      <p><strong>Контактная информация:</strong> <%= @vacancy.contacts %></p>
      <p><strong>Умения:</strong> <%= @vacancy.skills.map {|s| s.name}.join(', ') %> </p>
    </div>
    <%= link_to 'Редактировать', edit_vacancy_path(@vacancy) %> |
    <%= link_to 'К списку', vacancies_path %>
  </div>

  <div class="col-md-6">
    <% if @suitable_employees[:wholly].present? %>
      <div class="suitable-vacancies">
        <h3>Полностью подходящие работники:</h3>
        <div class="list-group">
          <% @suitable_employees[:wholly].each do |e| %>
              <a href="<%= employee_path(e) %>" class="list-group-item row">
                <div class="col-md-6"><%= e.name %></div>
                <div class="col-md-6 text-right"><%= e.salary %> руб.</div>
              </a>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @suitable_employees[:partially].present? %>
      <div class="suitable-vacancies">
        <h3>Частично подходящие работники:</h3>
        <div class="list-group">
          <% @suitable_employees[:partially].each do |e| %>
              <a href="<%= employee_path(e) %>" class="list-group-item row">
                <div class="col-md-6"><%= e.name %></div>
                <div class="col-md-6 text-right"><%= e.salary %> руб.</div>
              </a>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>

</div>